# reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# move cursor across panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# enable mouse support for fine-grained pane resizing
set -g mouse on

# resize panes
bind -n C-h resize-pane -L 8
bind -n C-j resize-pane -D 8
bind -n C-k resize-pane -U 8
bind -n C-l resize-pane -R 8

# enable vi/Vim style keybindings when in copy mode
set-window-option -g mode-keys vi

# retain current working directory when splitting panes
bind '"'  split-window -v -c "#{pane_current_path}"
bind %    split-window -h -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

# Beautifying tmux
set-option -g status-position bottom
set -g status-left ""
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_status_background "#3d3d3d"
set -g status-right "#{E:@catppuccin_status_application} #{E:@catppuccin_status_session}"

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
